### PR TITLE
fix: featured article image

### LINKED ISSUE #95: Featured article section in `articles` page seems a bit out of place if article's title/excerpt is short
Long title/excerpt:
image

Short title/excerpt:
image

In my opinion, when the title/excerpt is short, the featured article image is too big. Long and short title/excerpt should have same image size. Something like this:
image

Also apologize for out of topic, but the stackblitz link in readme is pointing to `docus-starter` instead of `alpine-starter`

### PR DESCRIPTION
**Pull request by LazyGeniusMan**
Closes #95

### CODE REVIEW

File: components/content/ArticlesListItem.vue [hunk 1]
```diff
@@ -24,9 +24,11 @@ defineProps({
 
 <template>
   <article v-if="article._path && article.title" :class="{ 'featured': featured }">
-    <NuxtLink :to="article._path">
-      <img v-if="article.cover" :src="article.cover">
-    </NuxtLink>
+    <div class="image">
+      <NuxtLink :to="article._path">
+        <img v-if="article.cover" :src="article.cover">
```
Comment (Atinux) [inline components/content/ArticlesListItem.vue:29]: We may want to also add the `alt` here

```suggestion
        <img v-if="article.cover" :src="article.cover" :alt="article.title">
```
